# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e98e396da12d8b7cd63f9b063932a91e90ef7bc8597b788d8f1416774efa73e337f08496f40b34908e4c11a76d7e15e1d1833dca276fff19a52815e792c1bb3

test:
  secret_key_base: 5f973c3051e18af8d9d81a98670a4b95c41b14705db2fba713dc105650bf0388494854228fdfe3d7ca3633be2ab358af29845963096b916aec7c90bbe799df8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
